# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: throwrocks.github.io
email: p0p.thr0w@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 The personal site of Jos√©. A FileMaker Certified Developer working with Food Services at Dallas ISD who rides a longboard after work and learns Android development at night.
baseurl: "" # the subpath of your site, e.g. /blog
url: "throwrocks.github.io" # the base hostname & protocol for your site
twitter_username: throwerror
github_username:  throwrocks

# Build settings
markdown: kramdown
